### ISSUE TITLE
Share collaboration link (share in explore or build mode)

### ISSUE THREAD

**Issue by JustMeGaaRa** [JustMeGaaRa/reverse-architecture-web#22]
### Tasks

- [ ] Share link popover on workspace page
- [ ] Save shared links in "Shared" tab on workspace explorer page
- [ ] Use access code for shared links to connect
